### ISSUE TITLE
Crashes when click on equalizer

### ISSUE THREAD

**Issue by cydia2020** [timusus/Shuttle#121]
**Shuttle version:**
 
 v2.00-b1
 
**Device, OS:**
 
Marlin - 7.1.2

**Description of bug:**
 ```
marlin:/ $ logcat
--------- beginning of main
08-14 09:38:27.088 19592 19592 I art     : Starting a blocking GC AddRemoveAppImageSpace
08-14 09:38:27.185 19592 19592 V Term    : onCreate
08-14 09:38:27.262 19592 19592 D Term    : TermService started
08-14 09:38:27.262 19592 19592 I TermService: Activity called onBind()
08-14 09:38:27.290 19592 19613 I Adreno  : QUALCOMM build                   : 6818200, Idb2b4cb785
08-14 09:38:27.290 19592 19613 I Adreno  : Build Date                       : 11/17/16
08-14 09:38:27.290 19592 19613 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
08-14 09:38:27.290 19592 19613 I Adreno  : Local Branch                     : N25
08-14 09:38:27.290 19592 19613 I Adreno  : Remote Branch                    :
08-14 09:38:27.290 19592 19613 I Adreno  : Remote Branch                    :
08-14 09:38:27.290 19592 19613 I Adreno  : Reconstruct Branch               :
08-14 09:38:27.295 19592 19613 I OpenGLRenderer: Initialized EGL, version 1.4
08-14 09:38:27.296 19592 19613 D OpenGLRenderer: Swap behavior 1
08-14 09:38:27.309 19592 19592 I Term    : Bound to TermService
08-14 09:38:27.309 19592 19592 I TermService: Activity binding to service
08-14 09:38:27.362 19592 19592 I libjackpal-androidterm: JNI_OnLoad
08-14 09:38:27.367 19592 19618 I Term    : waiting for: 19614
08-14 09:38:33.877 19592 19592 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
08-14 09:38:33.877 19592 19592 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-14 09:38:35.595 19592 19592 I Term    : Bound to TermService
08-14 09:38:35.595 19592 19592 I TermService: Activity binding to service
08-14 09:38:36.733 19592 19592 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
08-14 09:38:36.735 19592 19592 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-14 09:38:36.869 19592 19592 V Term    : onCreate
08-14 09:38:36.944 19592 19592 I Term    : Bound to TermService
08-14 09:38:36.944 19592 19592 I TermService: Activity binding to service
08-14 09:38:48.622 19592 19592 V Term    : onCreate
08-14 09:38:48.724 19592 19592 I Term    : Bound to TermService
08-14 09:38:48.724 19592 19592 I TermService: Activity binding to service
08-14 09:38:48.767 19592 19592 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-14 09:38:57.412 19592 19592 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
08-14 09:38:57.412 19592 19592 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-14 09:39:04.487 19592 19592 I Term    : Bound to TermService
08-14 09:39:04.487 19592 19592 I TermService: Activity binding to service
08-14 09:39:08.679 19592 19592 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1077852)
08-14 09:39:08.680 19592 19592 D AndroidRuntime: Shutting down VM
--------- beginning of crash
08-14 09:39:08.682 19592 19592 E AndroidRuntime: FATAL EXCEPTION: main
08-14 09:39:08.682 19592 19592 E AndroidRuntime: Process: jackpal.androidterm, PID: 19592
08-14 09:39:08.682 19592 19592 E AndroidRuntime: java.lang.RuntimeException: Failure from system
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4228)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4186)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4525)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4493)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at jackpal.androidterm.Term.doEmailTranscript(Term.java:999)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at jackpal.androidterm.Term.onOptionsItemSelected(Term.java:694)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Activity.onMenuItemSelected(Activity.java:3207)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1216)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1179)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3147)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:4062)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6171)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
08-14 09:39:08.682 19592 19592 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1077852 bytes
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3123)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
08-14 09:39:08.682 19592 19592 E AndroidRuntime:        ... 24 more
08-14 09:39:10.838 19927 19927 I art     : Starting a blocking GC AddRemoveAppImageSpace
08-14 09:39:10.864 19927 19927 V Term    : onCreate
08-14 09:39:10.968 19927 19927 D Term    : TermService started
08-14 09:39:10.969 19927 19927 I TermService: Activity called onBind()
08-14 09:39:11.010 19927 19944 I Adreno  : QUALCOMM build                   : 6818200, Idb2b4cb785
08-14 09:39:11.010 19927 19944 I Adreno  : Build Date                       : 11/17/16
08-14 09:39:11.010 19927 19944 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
08-14 09:39:11.010 19927 19944 I Adreno  : Local Branch                     : N25
08-14 09:39:11.010 19927 19944 I Adreno  : Remote Branch                    :
08-14 09:39:11.010 19927 19944 I Adreno  : Remote Branch                    :
08-14 09:39:11.010 19927 19944 I Adreno  : Reconstruct Branch               :
08-14 09:39:11.014 19927 19944 I OpenGLRenderer: Initialized EGL, version 1.4
08-14 09:39:11.014 19927 19944 D OpenGLRenderer: Swap behavior 1
08-14 09:39:11.025 19927 19927 I Term    : Bound to TermService
08-14 09:39:11.025 19927 19927 I TermService: Activity binding to service
08-14 09:39:11.078 19927 19927 I libjackpal-androidterm: JNI_OnLoad
08-14 09:39:11.089 19927 19949 I Term    : waiting for: 19945
08-14 09:39:17.854 19927 19927 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
08-14 09:39:17.854 19927 19927 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-14 09:39:30.316 19927 19927 I Term    : Bound to TermService
08-14 09:39:30.316 19927 19927 I TermService: Activity binding to service
```

**Comment by timusus** [comment]
04ae2502
