### ISSUE TITLE
Crash when pressing Cast button (when casting)

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#126]
**Shuttle version:**
 
 v2.0.0-beta1
 
**Device, OS:**
 
Nexus 6P, others.

**Description of bug:**
 
When pressing the Chromecast icon, the app crashes. Stacktrace attached at bottom.
 
**Steps to reproduce:**
 
 1. Start casting
 2. Press the cast button
 
**Other:**

This issue goes away if the Aesthetic Inflation Interceptor is disabled (by out-commenting `Aesthetic#106`). 

This may be related to the 'media route chooser', which appears when disconnecting from Chromecast. 
 
```
FATAL EXCEPTION: main
Process: com.simplecity.amp_pro.debug, PID: 24667
android.view.InflateException: Binary XML file line #41: Binary XML file line #41: Error inflating class ImageButton
Caused by: android.view.InflateException: Binary XML file line #41: Error inflating class ImageButton
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f01006a a=-1}
  at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
  at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
  at android.widget.ImageView.<init>(ImageView.java:188)
  at android.widget.ImageButton.<init>(ImageButton.java:86)
  at android.widget.ImageButton.<init>(ImageButton.java:82)
  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:73)
  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:69)
  at com.afollestad.aesthetic.AestheticImageButton.<init>(AestheticImageButton.java:24)
  at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.java:110)
  at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
  at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
  at android.support.v7.app.MediaRouteControllerDialog.onCreate(MediaRouteControllerDialog.java:336)
  at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
  at android.app.Dialog.show(Dialog.java:302)
  at android.support.v4.app.DialogFragment.onStart(DialogFragment.java:416)
  at android.support.v4.app.Fragment.performStart(Fragment.java:2369)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6541)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
  ```

**Comment by pwd-github** [comment]
I'm not sure if it's a different issue or this one still, but chromecast crashes every time you try and disconnect from a chromecast audio device.

**Comment by timusus** [comment]
Yep, that's this exact issue.
