### ISSUE TITLE
Crash whitelisting song

### ISSUE THREAD

**Issue by EmmanuelMess** [timusus/Shuttle#231]
**Shuttle version:**
 
 v2.0.0 beta 18
 
**Device, OS:**
 
Motorola Moto E Gen 2 4G, Marshmallow 6.0

**Description of bug:**
 
Crashes when pressing "Add to white list" on PopupMenu for song.
 
**Steps to reproduce:**
 
 0. Clean memory of app (I did this to assure that no other factors changed the outcome)
 1. Download [this](https://freemusicarchive.org/file/music/Music_for_Video/Circus_Marcus/Petites_pices/Circus_Marcus_-_04_-_Petite_pice_minime_No_2_-_Batifol.mp3) song.
 2. Put it under `/storage/[your sd card code]/Music/Circus_Marcus_-_04_-_Petite_pice_minime_No_2_-_Batifol.mp3`
 3. Press on it (toast appears)
 4. Select "Add as next" (nothing happens)
 5. Select "Add to white list" (Crash)

**Expected outcome:**
 
On step 4 the song should play (or be added as next). On step 5 a toast should probably appear telling the user that the song is already whitelisted (or there's no actual need for whitelisting).
 
**Observations/Actual Result:**
 
Crash:
```
11-28 15:11:58.258 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Circus_Marcus_-_04_-_Petite_pice_minime_No_2_-_Batifol.mp3
11-28 15:11:58.299 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:11:58.323 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Dee_Yan-Key_-_01_-_Non_troppo_vivo.mp3
11-28 15:11:58.351 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:11:58.361 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Dee_Yan-Key_-_02_-_Tranquillo_andante.mp3
11-28 15:11:58.378 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:11:58.389 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Dee_Yan-Key_-_03_-_Vivace_libero.mp3
11-28 15:11:58.403 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:11:58.416 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Kosta_T_-_02_-_.mp3
11-28 15:11:58.437 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:11:58.449 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Kosta_T_-_01_-__.mp3
11-28 15:11:58.463 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:11:58.477 28458-28627/com.simplecity.amp_pro.debug W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /storage/6B5C-B713/Music/Kosta_T_-_03_-_.mp3
11-28 15:11:58.496 28458-28627/com.simplecity.amp_pro.debug D/MediaPlayer: setSubtitleAnchor in MediaPlayer
11-28 15:12:02.101 28458-28458/com.simplecity.amp_pro.debug I/ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
11-28 15:12:03.252 28458-28458/com.simplecity.amp_pro.debug E/MenuUtils: getFileMenuClickListener threw error
                                                                         Throwable: No value present
11-28 15:12:03.257 28458-28458/com.simplecity.amp_pro.debug W/System.err: java.util.NoSuchElementException: No value present
11-28 15:12:03.258 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.annimon.stream.Optional.get(Optional.java:75)
11-28 15:12:03.258 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.simplecity.amp_library.utils.MenuUtils$$Lambda$26.apply(Unknown Source)
11-28 15:12:03.258 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
11-28 15:12:03.258 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.test(BehaviorRelay.java:354)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.emitFirst(BehaviorRelay.java:317)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.jakewharton.rxrelay2.BehaviorRelay.subscribeActual(BehaviorRelay.java:117)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-28 15:12:03.259 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-28 15:12:03.571 28458-28617/com.simplecity.amp_pro.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9ca5e70
11-28 15:12:03.572 28458-28617/com.simplecity.amp_pro.debug D/OpenGLRenderer: endAllActiveAnimators on 0xb9bb4fc0 (MenuPopupWindow$MenuDropDownListView) with handle 0xb9964c58
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: No value present
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:746)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-28 15:12:09.422 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err: Caused by: java.util.NoSuchElementException: No value present
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.annimon.stream.Optional.get(Optional.java:75)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.simplecity.amp_library.utils.MenuUtils$$Lambda$26.apply(Unknown Source)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.test(BehaviorRelay.java:354)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.emitFirst(BehaviorRelay.java:317)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at com.jakewharton.rxrelay2.BehaviorRelay.subscribeActual(BehaviorRelay.java:117)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
11-28 15:12:09.423 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-28 15:12:09.424 28458-28458/com.simplecity.amp_pro.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-28 15:12:09.433 28458-28458/com.simplecity.amp_pro.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.simplecity.amp_pro.debug, PID: 28458
                                                                              io.reactivex.exceptions.OnErrorNotImplementedException: No value present
                                                                                  at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                                  at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                                  at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
                                                                                  at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
                                                                                  at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                  at android.os.Handler.handleCallback(Handler.java:746)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                               Caused by: java.util.NoSuchElementException: No value present
                                                                                  at com.annimon.stream.Optional.get(Optional.java:75)
                                                                                  at com.simplecity.amp_library.utils.MenuUtils$$Lambda$26.apply(Unknown Source)
                                                                                  at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
                                                                                  at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
                                                                                  at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                                                                                  at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
                                                                                  at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
                                                                                  at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
                                                                                  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
                                                                                  at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.test(BehaviorRelay.java:354)
                                                                                  at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.emitFirst(BehaviorRelay.java:317)
                                                                                  at com.jakewharton.rxrelay2.BehaviorRelay.subscribeActual(BehaviorRelay.java:117)
                                                                                  at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                                  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                                  at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by timusus** [comment]
Thanks for the detailed report, will be fixed soon.
