### ISSUE TITLE
Shuttle is crashes when try to add Artist folder's song to the playlist

### ISSUE THREAD

**Issue by sagorahmed** [timusus/Shuttle#350]
#### Expected behavior
I expected that using this app I will able to add music to the playlist from "ARTIST" tabs folder.
#### Actual behavior
When I try to add songs of Artist's folder to the playlist, the app crashes after a moment.
#### How to reproduce
* Download and install the latest v2.0.5-beta2 <a href="https://github.com/timusus/Shuttle/releases" >from here </a>
* Open the app and go to ARTIST tab.
* You will see many folders, tap and open a folder (as your choice).
* Then tap "three dots" button on the top.
* Then press "Add to..." and after that tap on "Playlist".
* Select a playlist where you want to add your songs and then notice the crash.
* App version: 2.0.5 beta2 free
* Operating system: Android 6.0.1
* Device: Samsung Galaxy A5 (2016)

#### Recording Of The Bug
![gif_image.gif](https://cdn.steemitimages.com/DQmUQRTEn1WZm6XsoGmYn1ckffYUfMU5LT5E13x6mWP4SXL/gif_image.gif)
#### GitHub Account
https://github.com/sagorahmed
#### Logcat
```05-31 13:41:47.211 18739 18739 E AndroidRuntime: FATAL EXCEPTION: main

05-31 13:41:47.211 18739 18739 E AndroidRuntime: Process: another.music.player, PID: 18739

05-31 13:41:47.211 18739 18739 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.res.ColorStateList.getColorForState(int[], int)' on a null object reference

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.support.design.widget.CustomCollapsingTextHelper.getCurrentCollapsedTextColor(SourceFile:462)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.support.design.widget.CustomCollapsingTextHelper.calculateOffsets(SourceFile:426)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.support.design.widget.CustomCollapsingTextHelper.calculateCurrentOffsets(SourceFile:400)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.support.design.widget.CustomCollapsingTextHelper.recalculate(SourceFile:781)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.support.design.widget.CustomCollapsingTextHelper.setCollapsedTextColor(SourceFile:842)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.support.design.widget.CustomCollapsingToolbarLayout.setCollapsedTitleTextColor(SourceFile:781)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.ui.detail.artist.ArtistDetailFragment$3.b(SourceFile:511)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.ui.detail.artist.ArtistDetailFragment.g(SourceFile:707)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.ui.detail.artist.a.b(SourceFile:70)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.ui.detail.artist.ArtistDetailFragment.o(SourceFile:339)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.ui.detail.artist.ArtistDetailFragment.lambda$QJedE_OneAPjTgswUbFItWwimyE(SourceFile)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.ui.detail.artist.-$$Lambda$ArtistDetailFragment$QJedE_OneAPjTgswUbFItWwimyE.run(lambda)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.utils.z.a(SourceFile:393)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.utils.z.a(SourceFile:364)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.utils.z.lambda$6MZlgz3hldLNR3U7R5D7nHxgc1U(SourceFile)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.simplecity.amp_library.utils.-$$Lambda$z$6MZlgz3hldLNR3U7R5D7nHxgc1U.accept(lambda)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at c.b.f.d.h.c_(SourceFile:63)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at c.b.f.e.e.m$a.run(SourceFile:81)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at c.b.a.b.b$b.run(SourceFile:109)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

05-31 13:41:47.211 18739 18739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) ```

**Comment by GeoZac** [comment]
Unable to reproduce on v2.0.5
