### ISSUE TITLE
The application crashes when clicking the Upgrade feature

### ISSUE THREAD

**Issue by ahyar92** [timusus/Shuttle#455]
### Expected behavior
Supposedly, when I click the Upgrade feature, the application will not experience errors or crashes

### Actual behavior
When I tried clicking the "Upgrade" feature, the application suddenly crashed

### How to reproduce
1. Install and open the application
2. Click on the "Folder" menu to bring up the "upgrade" feature.
3. Then then click on "Upgrade", then an error will appear

### Environment
Tested on  1 devices:

<table>
<thead>
<tr><th>Device</th><th>Android Version</th>
</thead>
<tbody>
<tr><td>VIVO Y81</td><td>Oreo 8.1.0 (CPU: Octa-core Max 2.0 GHz, RAM: 3 GB)</td>
</table>

### Recording Of The Bug
You can see the recording below:
https://youtu.be/bxgDPXgIbPk

### Logcat
```
--------- beginning of crash
04-02 01:20:25.264  6670  6670 E AndroidRuntime: FATAL EXCEPTION: main
04-02 01:20:25.264  6670  6670 E AndroidRuntime: Process: another.music.player, PID: 6670
04-02 01:20:25.264  6670  6670 E AndroidRuntime: d.h: lateinit property billingManager has not been initialized
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at com.simplecity.amp_library.ui.c.k.a(SourceFile:17)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at com.simplecity.amp_library.ui.c.k$b.onClick(SourceFile:33)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at com.afollestad.materialdialogs.f.onClick(SourceFile:410)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at android.view.View.performClick(View.java:6325)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25098)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:192)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6779)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
04-02 01:20:25.264  6670  6670 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)
04-02 01:20:25.295  6670  6715 E         : nFreeSize: 1044127744
```

**Comment by timusus** [comment]
Fixed in v2.0.12-beta2
